# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [ ]:
l=s.split()
print(l)

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [ ]:
txt = "The diameter of {name} is {distance} kilometers".format(name = planet, distance = diameter)
txt

'The diameter of Earth is 12742 kilometers'

## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
print(d['k1'][3]['tricky'][3]['target'][3])

hello

# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros")
array

An array of 10 zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
array=np.ones(10)*5
print("An array of 10 fives")
array

An array of 10 fives

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [ ]:
li=[]
for i in range(20,35):
  if(i%2==0):
    li.append(i)
li

[20, 22, 24, 26, 28, 30, 32, 34]

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
import random
a=[[0]*3]*3
for i in range(3):
  for j in range(3):
    a[i][j]=random.randint(0,9)
a

[[6, 9, 8], [6, 9, 8], [6, 9, 8]]

## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
final = np.concatenate((a, b), axis = None)
  
print (final)

[1 2 3 4 5 6]

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame(index=['1','2','3'], columns=['1','2'])
df

     1    2
1  NaN  NaN
2  NaN  NaN
3  NaN  NaN

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
import pandas as pd
from datetime import datetime

pd.date_range(start="2023-01-01",end="2023-02-10").to_pydatetime().tolist()

[datetime.datetime(2023, 1, 1, 0, 0),
 datetime.datetime(2023, 1, 2, 0, 0),
 datetime.datetime(2023, 1, 3, 0, 0),
 datetime.datetime(2023, 1, 4, 0, 0),
 datetime.datetime(2023, 1, 5, 0, 0),
 datetime.datetime(2023, 1, 6, 0, 0),
 datetime.datetime(2023, 1, 7, 0, 0),
 datetime.datetime(2023, 1, 8, 0, 0),
 datetime.datetime(2023, 1, 9, 0, 0),
 datetime.datetime(2023, 1, 10, 0, 0),
 datetime.datetime(2023, 1, 11, 0, 0),
 datetime.datetime(2023, 1, 12, 0, 0),
 datetime.datetime(2023, 1, 13, 0, 0),
 datetime.datetime(2023, 1, 14, 0, 0),
 datetime.datetime(2023, 1, 15, 0, 0),
 datetime.datetime(2023, 1, 16, 0, 0),
 datetime.datetime(2023, 1, 17, 0, 0),
 datetime.datetime(2023, 1, 18, 0, 0),
 datetime.datetime(2023, 1, 19, 0, 0),
 datetime.datetime(2023, 1, 20, 0, 0),
 datetime.datetime(2023, 1, 21, 0, 0),
 datetime.datetime(2023, 1, 22, 0, 0),
 datetime.datetime(2023, 1, 23, 0, 0),
 datetime.datetime(2023, 1, 24, 0, 0),
 datetime.datetime(2023, 1, 25, 0, 0),
 datetime.datetime(2023, 1, 26, 0, 0),
 datetime.datetime(2023, 1, 27, 0, 0),
 datetime.datetime(2023, 1, 28, 0, 0),
 datetime.datetime(2023, 1, 29, 0, 0),
 datetime.datetime(2023, 1, 30, 0, 0),
 datetime.datetime(2023, 1, 31, 0, 0),
 datetime.datetime(2023, 2, 1, 0, 0),
 datetime.datetime(2023, 2, 2, 0, 0),
 datetime.datetime(2023, 2, 3, 0, 0),
 datetime.datetime(2023, 2, 4, 0, 0),
 datetime.datetime(2023, 2, 5, 0, 0),
 datetime.datetime(2023, 2, 6, 0, 0),
 datetime.datetime(2023, 2, 7, 0, 0),
 datetime.datetime(2023, 2, 8, 0, 0),
 datetime.datetime(2023, 2, 9, 0, 0),
 datetime.datetime(2023, 2, 10, 0, 0)]

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
df = pd.DataFrame(lists, columns=['1', '2','3'])
df

   1    2   3
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24